In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("full_df.csv")
df.head()

,Unnamed: 0,id,x,y,w,h,l1x,l1y,l1v,l2x,...,l3y,l3v,l4x,l4y,l4v,l5x,l5y,l5v,im_w,im_h
0,0,0--Parade/0_Parade_marchingband_1_849.jpg,449.0,330.0,122.0,149.0,488.906,373.643,True,542.089,...,412.830,True,485.174,425.893,True,538.357,431.491,True,1024,1385
1,1,0--Parade/0_Parade_Parade_0_904.jpg,361.0,98.0,263.0,339.0,424.143,251.656,True,547.134,...,325.875,True,453.830,368.286,True,561.978,342.839,True,1024,1432
2,2,0--Parade/0_Parade_marchingband_1_799.jpg,78.0,221.0,7.0,8.0,-1.000,-1.000,False,-1.000,...,-1.000,False,-1.000,-1.000,False,-1.000,-1.000,False,1024,768
3,3,0--Parade/0_Parade_marchingband_1_799.jpg,78.0,238.0,14.0,17.0,84.188,244.607,True,89.527,...,247.857,True,85.116,250.643,True,88.482,250.643,True,1024,768
4,4,0--Parade/0_Parade_marchingband_1_799.jpg,113.0,212.0,11.0,15.0,117.000,220.000,True,122.000,...,222.000,True,118.000,225.000,True,122.000,225.000,True,1024,768

In [6]:
df[(df["l1v"] == -1)]*df["l1x"]

Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]
Index: []

[0 rows x 159447 columns]